server:
  port: 10000

spring:
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoningli/spring-cloud-config
          username: xiaoningli
          password: ln1987ln
          basedir: ./data # 本地库目录
eureka:
  instance:
    instance-id: config-api
  client:
    service-url:
      defaultZone: http://eureka01:9000/eureka/  # 注册中心访问地址