spring:
  application:
    name: GOODS
server:
  port: 8082

eureka:
  instance:
    instance-id: goods-api-8082
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://eureka01:9000/eureka/ # 注册中心访问地址